package com.gmail.abhishekdas1503.email.popularmovies.model;

/**
 * Response as generated by the movieDB API. This will be returned by the Callable
 * method and it's member results will be used by the app to render the movies.
 *
 * Note: movieDB people named the JSON Array within the response as "results" instead
 * of "movies" and since the class has been auto-generated with the help of an online
 * JSONObject to POJO <a href="http://www.jsonschema2pojo.org/">Converter</a> , there
 * are some naming problems b/w results and movies.
 */

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

public class MovieResponse {

    @Expose
    private Integer page;
    @Expose
    @SerializedName("results")
    private List<Movie> movies = new ArrayList<Movie>();
    @SerializedName("total_pages")
    @Expose
    private Integer totalPages;
    @SerializedName("total_results")
    @Expose
    private Integer totalMovies;

    /**
     *
     * @return
     * The page
     */
    public Integer getPage() {
        return page;
    }

    /**
     *
     * @param page
     * The page
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     *
     * @return
     * The results
     */
    public List<Movie> getMovies() {
        return movies;
    }

    /**
     *
     * @param movies
     * The results
     */
    public void setMovies(List<Movie> movies) {
        this.movies = movies;
    }

    /**
     *
     * @return
     * The totalPages
     */
    public Integer getTotalPages() {
        return totalPages;
    }

    /**
     *
     * @param totalPages
     * The total_pages
     */
    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    /**
     *
     * @return
     * The totalMovies
     */
    public Integer getTotalMovies() {
        return totalMovies;
    }

    /**
     *
     * @param totalMovies
     * The total_results
     */
    public void setTotalMovies(Integer totalMovies) {
        this.totalMovies = totalMovies;
    }

}